### ISSUE TITLE
Cmake is missing GEOIP_LIBRARY and SDL2MAIN_LIBRARY

### ISSUE THREAD

**Issue by cengique** [GrangerHub/Stellar-Prey#2]
In the result of `./sp-tools.sh configure_cmake both`
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GEOIP_LIBRARY (ADVANCED)
    linked by target "OWMaster" in directory /home/cengiz/sw_nobackup/grangerhub/Stellar-Prey/source/OpenWolf-Engine
SDL2MAIN_LIBRARY
    linked by target "client" in directory /home/cengiz/sw_nobackup/grangerhub/Stellar-Prey/source/OpenWolf-Engine
    linked by target "server" in directory /home/cengiz/sw_nobackup/grangerhub/Stellar-Prey/source/OpenWolf-Engine
    linked by target "engine" in directory /home/cengiz/sw_nobackup/grangerhub/Stellar-Prey/source/OpenWolf-Engine
    linked by target "autoupdateserver" in directory /home/cengiz/sw_nobackup/grangerhub/Stellar-Prey/source/OpenWolf-Engine
```
I assume these are libraries that need to be installed prior?

**Comment by cengique** [comment]
@TheDushan I installed GeoIP, but there seems to be a problem with SDL2MAIN. It could be just for Windows. There is some info [here](https://trenki2.github.io/blog/2017/06/02/using-sdl2-with-cmake/).

**Comment by cengique** [comment]
These are coming from under the OpenWolfEngine submodule, so this issue should probably have been opened for that repo.

**Comment by dGr8LookinSparky** [comment]
@cengique , is the issue you are having with SDL2 on Linux or Windows, or both?  I know that I had to install some additional dependencies for building this project on Ubuntu 20.04 (and I am able to successfully build all of the binaries on my Ubuntu installation), although I forgot exactly which ones and didn't take note at the time.  We definitely should take note in the README of the required additional dependencies for each supported platform.

**Comment by cengique** [comment]
@dGr8LookinSparky we spoke with @TheDushan and I opened a [pull request](https://github.com/TheDushan/OpenWolf-Engine/pull/5) on the OpenWolf repo for this.

**Comment by dGr8LookinSparky** [comment]
It's merged in with this commit: https://github.com/GrangerHub/Stellar-Prey/commit/6c4c3a68a3bc39b205e0382ad25acf9537174840
